import Image from 'next/image';
import Link from 'next/link';
import { brand } from '@/config/brand';
import { services } from '@/config/project';
const steps=[['01','Parlez-nous de votre intérieur','Décrivez votre pièce, vos besoins et votre rythme de vie.'],['02','Partagez vos éléments','Photos, mesures, documents et inspirations restent réunis dans votre dossier.'],['03','Suivez votre projet','Rendez-vous, demandes de complément et avancée sont visibles depuis votre espace.']];
export default function Home(){return <main>
<section className="shell grid min-h-[72vh] items-center gap-12 py-12 lg:grid-cols-[1.05fr_.95fr] lg:py-20"><div><p className="text-xs font-bold uppercase tracking-[.28em] text-gold">Décoration d’intérieur · accompagnement personnalisé</p><h1 className="mt-5 font-serif text-5xl leading-[1.03] text-forest md:text-7xl">{brand.heroTitle}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-ink/70">{brand.heroText}</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/inscription" className="rounded-full bg-forest px-6 py-3 text-white">Démarrer mon projet</Link><Link href="/prestations" className="rounded-full border border-forest/25 bg-white/50 px-6 py-3">Découvrir les prestations</Link></div></div><div className="card overflow-hidden p-4"><Image src={brand.logoPath} alt={`${brand.brandName} ${brand.brandTagline}`} width={1024} height={1024} className="aspect-square w-full rounded-2xl object-cover" priority/></div></section>
<section className="bg-white/50 py-20"><div className="shell"><p className="text-xs font-bold uppercase tracking-[.28em] text-gold">Un parcours simple</p><h2 className="mt-3 font-serif text-4xl text-forest">Votre projet, organisé sans surcharge.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{steps.map(([n,t,d])=><article className="card p-7" key={n}><div className="text-sm text-gold">{n}</div><h3 className="mt-5 font-serif text-2xl text-forest">{t}</h3><p className="mt-3 leading-7 text-ink/65">{d}</p></article>)}</div></div></section>
<section className="shell py-20"><div className="flex items-end justify-between gap-6"><div><p className="text-xs font-bold uppercase tracking-[.28em] text-gold">Prestations</p><h2 className="mt-3 font-serif text-4xl text-forest">À chaque besoin, un accompagnement adapté.</h2></div><Link className="hidden md:block text-sm underline" href="/prestations">Voir toutes les prestations</Link></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{services.slice(0,8).map((s)=><div key={s} className="rounded-2xl border border-forest/10 bg-cream/55 p-5 font-medium text-forest">{s}</div>)}</div></section>
<section className="bg-forest py-20 text-ivory"><div className="shell grid gap-8 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.28em] text-gold">Suivi privé</p><h2 className="mt-3 font-serif text-4xl">Tout votre dossier au même endroit.</h2></div><div className="grid gap-3 text-ivory/75 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 p-5">Photos et documents privés</div><div className="rounded-2xl border border-white/10 p-5">Questionnaire progressif</div><div className="rounded-2xl border border-white/10 p-5">Rendez-vous liés au projet</div><div className="rounded-2xl border border-white/10 p-5">Chronologie et messages</div></div></div></section>
</main>}
